spring:
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  redis:
    port: 6379
    host: localhost
  messages: # 메시지, 에러 메시지 설정
    basename: messages, errors
  mvc: # Swagger 설정
    pathmatch:
      matching-strategy: ant_path_matcher
  jwt:
    #  1000(1초) * 60 * 60 * 2 = 2시간
    accessTokenExpiration: 5 # "#{1000 * 60 * 60 * 2}"
    #  1000(1초) * 60 * 60 * 24 * 14 = 2주
    refreshTokenExpiration: "#{1000 * 60 * 60 * 24 * 14}"

logging.level:
  org.hibernate.SQL: debug

